on: push
name: 🚀 Laravel
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: https://jissoftware.in/
          username: jissoftware
          password: uA&uOxJ@Mnye
          server-dir: /home/jissoftware/public_html/mram
